collect_database:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/HuiCollect?charset=utf8mb4"

monitor_hui_blocks_db:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/block_data_test?charset=utf8mb4"

monitor_eth_blocks_db:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/block_eth_test?charset=utf8mb4"

monitor_bsc_blocks_db:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/block_bsc_test?charset=utf8mb4"

monitor_btc_blocks_db:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/block_btc_test?charset=utf8mb4"

monitor_tron_blocks_db:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/block_tron_test?charset=utf8mb4"

server_conf:
  port: 8010

chains:
  Hui:
    id: 8888
    rpc_url: "http://43.198.66.226:8545"
    fetch_timeout: 3000

UserInfo:
  KycPubKey: "026a38b8aa47f2af2d2163253ff5385cd059f90476990c7e3ee84bca0ead322241"
  url: "https://fat.huiwang.io/registrar/"

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "/tmp/app.log"
    level: 4
  kafka:
    enable: false
    topic: "Hui-test"
    kafka_servers:
      - "kafka-1.Hui.com:9092"
      - "kafka-2.Hui.com:9092"
      - "kafka-3.Hui.com:9092"
    level: 3
