database:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/EthCollect?charset=utf8mb4"

monitor:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/block_eth_test?charset=utf8mb4"

server_conf:
  port: 8010

chain:
  name: "ETH"

UserInfo:
  KycPubKey: "026a38b8aa47f2af2d2163253ff5385cd059f90476990c7e3ee84bca0ead322241"
  url: "https://fat.huiwang.io/registrar/"

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "/tmp/app.log"
    level: 4
  kafka:
    enable: false
    topic: "Hui-test"
    kafka_servers:
      - "kafka-1.Hui.com:9092"
      - "kafka-2.Hui.com:9092"
      - "kafka-3.Hui.com:9092"
    level: 3
