collect_database:
  hui_db : "root:csquan253905@tcp(127.0.0.1:3306)/HuiCollect?charset=utf8mb4"
  tron_db : "root:csquan253905@tcp(127.0.0.1:3306)/TronCollect?charset=utf8mb4"

walletInfo:
  url:  http://54.254.77.93:31218/v1

server_conf:
  port: 8010

query_interval:
    30000
chains:
  Hui:
    id: 8888
    rpc_url: "http://43.198.66.226:8545"
    fetch_timeout: 6000

KafkaInfo:
  url:
    - 192.168.31.242:9092
  user: ""
  pass: ""
  tls: false
  groupId: monitor_group
  topic_account: registrar-user-created
  topic_tx: MonitorTx0

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "/tmp/app.log"
    level: 4
  kafka:
    enable: false
    topic: "Hui-test"
    kafka_servers:
      - "kafka-1.Hui.com:9092"
      - "kafka-2.Hui.com:9092"
      - "kafka-3.Hui.com:9092"
    level: 3
